export const generalConstants = {
    selectType: 'Select Type',
    selectProficiency: 'Select Proficiency',
    selectCategory: 'Select Category',
    selectSkill: 'Select Skill',
    selectSubSkill: 'Select Sub Skill',
    search: 'Search',
    advanced: 'Advanced',
    proficiency: 'Proficiency',
    assessments: 'Assessments',
    userAttempted: 'User Attempted',
    score: 'Score',
    duration: 'Duration',
    avgTimeTaken: 'Average Time Taken',
    author: 'Author',
    createdOn: 'Created On',
    modifiedOn: 'Modified On',
    publishedDate: 'Published Date',
    reviewer: 'Reviewer',
    questionAge: 'Question Age',
    attemptSummary: 'Attempt Summary',
    description: 'Description',
    multipleChoiceOptions: 'Multiple Choice Options',
    hints: 'Hints',
    total: 'Total',
    type: 'Type',
    loadMore: 'Load More'
}